# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9bdbabcc0c97e91c27a9e3b1bdf0b0df2ae5795d381a0aa70f6ea8a1fbdde45ee97c64a4540bf3684547b336a7752f3dcccf50bf210949a4a838822fd820354f

test:
  secret_key_base: 2a91f1e2d06d85d6a82b6d9979a3e041ef115ad43a5cfea04c3e6707d750044410120040b2d0891c643af2cd7a2a1a8b88fe461c62efd1abe9ad347af94e5db5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
